site_name: Extended SDK Documentation
site_url: https://amoam-vr.github.io/fortressdocs
site_name: Fortress Docs
nav:
  - Home: index.md
  - Scripts:
    - Cylinder Grip: cylindergrip.md
theme:
  name: material
  custom_dir: overrides
